# Generated by Django 5.1.4 on 2025-02-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.ImageField(upload_to='')),
                ('c_pass', models.IntegerField()),
            ],
        ),
    ]
