# Generated by Django 5.1.4 on 2025-02-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0003_login_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_data',
            new_name='login_view',
        ),
    ]
