# Generated by Django 5.1.6 on 2025-02-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0005_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
