# Generated by Django 5.1.6 on 2025-03-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0008_audio_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='city_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='audio',
        ),
    ]
