# Generated by Django 5.1.6 on 2025-03-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0009_city_delete_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
