# Generated by Django 5.1.6 on 2025-03-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0010_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('artist', models.CharField(default='Unknown Artist', max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
    ]
