# Generated by Django 5.1.6 on 2025-03-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0012_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monument_name', models.CharField(max_length=30)),
                ('info_english', models.TextField()),
                ('charges', models.IntegerField()),
                ('contact_no', models.BigIntegerField()),
                ('timing', models.CharField(max_length=30)),
                ('days', models.CharField(max_length=30)),
                ('map_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='monument_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='monument photos')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio.monument')),
            ],
        ),
    ]
