# Generated by Django 5.1.6 on 2025-03-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0014_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='monument_photos',
            name='monument',
        ),
        migrations.DeleteModel(
            name='monument',
        ),
        migrations.DeleteModel(
            name='monument_photos',
        ),
    ]
