# Generated by Django 5.1.6 on 2025-03-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0016_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Booking_data',
        ),
    ]
