# Generated by Django 5.1.6 on 2025-03-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0018_booking_delete_booking_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
