# Generated by Django 5.1.6 on 2025-03-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0020_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
