# Generated by Django 5.1.6 on 2025-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0022_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('adalaj-stepwell', 'Adalaj Stepwell'), ('rani-ki-vav', 'Rani Ki Vav'), ('vintage-car-museum', 'The Vintage Car Museum'), ('sabarmati-aashram', 'Sabarmati Aashram'), ('hutheesing-jain-temple', 'Hutheesing Jain Temple'), ('jama-masjid', 'Jama Masjid'), ('jhulta-minar', 'Jhulta Minar'), ('kankaria-lake', 'Kankaria Lake'), ('lal-darvaja', 'Lal Darvaja'), ('sabarmati-riverfront', 'Sabarmati Riverfront')], max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
